# services:
#   eureka-server:
#     build:
#       context: ../backend/eureka-server
#     image: eureka-server:latest
#     ports:
#       - "8761:8761"
#     networks:
#       - app_network

#   gateway:
#     build:
#       context: ../backend/gateway
#     image: gateway:latest
#     ports:
#       - "8080:8082"
#     depends_on:
#       - eureka-server
#       - mysql-db
#     networks:
#       - app_network

#   ambulance-service:
#     build:
#       context: ../backend/ambulance-service
#     image: ambulance-service:latest
#     ports:
#       - "8081:8080"
#     depends_on:
#       - eureka-server
#       - mysql-db  
#     networks:
#       - app_network

#   hospital-service:
#     build:
#       context: ../backend/hospital-service
#     image: hospital-service:latest
#     ports:
#       - "8082:8083"
#     depends_on:
#       - eureka-server
#       - mysql-db  
#     networks:
#       - app_network

#   patient-service:
#     build:
#       context: ../backend/patient-service
#     image: patient-service:latest
#     ports:
#       - "8083:8084"
#     depends_on:
#       - eureka-server
#       - mysql-db  
#     networks:
#       - app_network

#   routing-service:
#     build:
#       context: ../backend/routing-service
#     image: routing-service:latest
#     ports:
#       - "8084:8085"
#     depends_on:
#       - eureka-server
#       - mysql-db  
#     networks:
#       - app_network

#   frontend:
#     build:
#       context: ../frontend
#     image: frontend:latest
#     ports:
#       - "8086:80"
#     networks:
#       - app_network

#   mysql-db:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: 1234
#       MYSQL_DATABASE: ambulance_app
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql
#     networks:
#       - app_network

# volumes:
#   mysql-data:

# networks:
#   app_network:
#     driver: bridge

#todo : best v
# version: '3.8'
# services:
#   jenkins:
#     image: jenkins/jenkins:lts
#     container_name: jenkins
#     ports:
#       - "9191:8080"
#       - "50000:50000"
#     volumes:
#       - jenkins_data:/var/jenkins_home
#       - /var/run/docker.sock:/var/run/docker.sock

#   eureka-server:
#     build:
#       context: ../backend/eureka-server
#     image: eureka-server:latest
#     ports:
#       - "8761:8761"
#     networks:
#       - app_network

#   gateway:
#     build:
#       context: ../backend/gateway
#     image: gateway:latest
#     ports:
#       - "8080:8082"
#     depends_on:
#       - eureka-server
#       - mysql-db
#     networks:
#       - app_network

#   ambulance-service:
#     build:
#       context: ../backend/ambulance-service
#     image: ambulance-service:latest
#     ports:
#       - "8081:8080"
#     depends_on:
#       - eureka-server
#       - mysql-db  
#     networks:
#       - app_network

#   hospital-service:
#     build:
#       context: ../backend/hospital-service
#     image: hospital-service:latest
#     ports:
#       - "8082:8083"
#     depends_on:
#       - eureka-server
#       - mysql-db  
#     networks:
#       - app_network

#   patient-service:
#     build:
#       context: ../backend/patient-service
#     image: patient-service:latest
#     ports:
#       - "8083:8084"
#     depends_on:
#       - eureka-server
#       - mysql-db  
#     networks:
#       - app_network

#   routing-service:
#     build:
#       context: ../backend/routing-service
#     image: routing-service:latest
#     ports:
#       - "8084:8085"
#     depends_on:
#       - eureka-server
#       - mysql-db  
#     networks:
#       - app_network

#   frontend:
#     build:
#       context: ../frontend
#     image: frontend:latest
#     ports:
#       - "8086:80"
#     networks:
#       - app_network

#   mysql-db:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: 1234
#       MYSQL_DATABASE: ambulance_app
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql
#     networks:
#       - app_network

# volumes:
#   mysql-data:
#   jenkins_data:

# networks:
#   app_network:
#     driver: bridge

# version: '3.8'
# services:
#   jenkins:
#     image: jenkins/jenkins:lts
#     container_name: jenkins
#     ports:
#       - "9191:8080"
#       - "50000:50000"
#     volumes:
#       - jenkins_data:/var/jenkins_home
#       - /var/run/docker.sock:/var/run/docker.sock

#   jenkins-agent:  
#     image: jenkins/inbound-agent:latest
#     container_name: jenkins-agent
#     depends_on:
#       - jenkins
#     environment:
#       JENKINS_AGENT_WORKDIR: /home/jenkins/agent 
#       JENKINS_URL: http://jenkins:8080
#       JENKINS_SECRET: "OWlS9EmF+kGxgi5Wa/ql/g=="
#       JENKINS_AGENT_NAME: docker-agent
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     networks:
#       - app_network

#   eureka-server:
#     build:
#       context: ../backend/eureka-server
#     image: eureka-server:latest
#     ports:
#       - "8761:8761"
#     networks:
#       - app_network

#   gateway:
#     build:
#       context: ../backend/gateway
#     image: gateway:latest
#     ports:
#       - "8080:8082"
#     depends_on:
#       - eureka-server
#       - mysql-db
#     networks:
#       - app_network

#   ambulance-service:
#     build:
#       context: ../backend/ambulance-service
#     image: ambulance-service:latest
#     ports:
#       - "8081:8080"
#     depends_on:
#       - eureka-server
#       - mysql-db  
#     networks:
#       - app_network

#   hospital-service:
#     build:
#       context: ../backend/hospital-service
#     image: hospital-service:latest
#     ports:
#       - "8082:8083"
#     depends_on:
#       - eureka-server
#       - mysql-db  
#     networks:
#       - app_network

#   patient-service:
#     build:
#       context: ../backend/patient-service
#     image: patient-service:latest
#     ports:
#       - "8083:8084"
#     depends_on:
#       - eureka-server
#       - mysql-db  
#     networks:
#       - app_network

#   routing-service:
#     build:
#       context: ../backend/routing-service
#     image: routing-service:latest
#     ports:
#       - "8084:8085"
#     depends_on:
#       - eureka-server
#       - mysql-db  
#     networks:
#       - app_network

#   frontend:
#     build:
#       context: ../frontend
#     image: frontend:latest
#     ports:
#       - "8086:80"
#     networks:
#       - app_network

#   mysql-db:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: 1234
#       MYSQL_DATABASE: ambulance_app
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql
#     networks:
#       - app_network

# volumes:
#   mysql-data:
#   jenkins_data:

# # networks:
# #   app_network:
# #     driver: bridge

# networks:
#   docker_app_network:
#     external: true

version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9191:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_app_network

  jenkins-agent:  
    # image: jenkins/inbound-agent:latest
    build:
      context: ../jenkins-agent
    container_name: jenkins-agent
    depends_on:
      - jenkins
    environment:
      JENKINS_AGENT_WORKDIR: /home/jenkins/agent 
      JENKINS_URL: http://jenkins:8080
      JENKINS_SECRET: "4343e2777994140c67574fb05f3deb705b34674bd69a5122708474b8d94b16f0"
      JENKINS_AGENT_NAME: docker-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_app_network

  eureka-server:
    build:
      context: ../backend/eureka-server
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - docker_app_network

  gateway:
    build:
      context: ../backend/gateway
    image: gateway:latest
    ports:
      - "8080:8082"
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - docker_app_network

  ambulance-service:
    build:
      context: ../backend/ambulance-service
    image: ambulance-service:latest
    ports:
      - "8081:8080"
    depends_on:
      - eureka-server
      - mysql-db  
    networks:
      - docker_app_network

  hospital-service:
    build:
      context: ../backend/hospital-service
    image: hospital-service:latest
    ports:
      - "8082:8083"
    depends_on:
      - eureka-server
      - mysql-db  
    networks:
      - docker_app_network

  patient-service:
    build:
      context: ../backend/patient-service
    image: patient-service:latest
    ports:
      - "8083:8084"
    depends_on:
      - eureka-server
      - mysql-db  
    networks:
      - docker_app_network

  routing-service:
    build:
      context: ../backend/routing-service
    image: routing-service:latest
    ports:
      - "8084:8085"
    depends_on:
      - eureka-server
      - mysql-db  
    networks:
      - docker_app_network

  frontend:
    build:
      context: ../frontend
    image: frontend:latest
    ports:
      - "8086:80"
    networks:
      - docker_app_network

  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ambulance_app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - docker_app_network

volumes:
  mysql-data:
  jenkins_data:

networks:
  docker_app_network:
    # external: true
    driver: bridge