pipeline {
    agent any
    tools {
        jdk 'JDK 17'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'your_git_repo_url', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                sh './mvnw clean install'
            }
        }
         stage('Test') {
             steps {
                 sh './mvnw test'
             }
        }
        stage('SonarQube Analysis') {
             steps {
                  withSonarQubeEnv('Sonar') {
                    sh './mvnw sonar:sonar'
                 }
             }
        }
        stage('Docker Build') {
            steps {
               script{
                def imageName = "your_docker_registry/your_image_name:\"
                sh "docker build -t \ ."
                sh "docker push \"
                }
            }
        }
        stage('Deploy') {
             steps {
                  sh 'docker-compose up -d'
             }
        }
    }
}
