package com.example.routingservice.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "routings") // Customize if needed
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Routing {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String fromService;
    private String toService;
    private String criteria;  // Could be a JSON/String representation of routing rules
    private String decision; // You could track the decision that this routing rule lead to

    // Getters and Setters generated by Lombok annotations
}